Fixing and updating script for TWE DI-435
eastgenomics/RD_requests pull request #14
Opened 2024-11-15 16:58 UTC by RSWilson1

Added matching dates based on b37 projects instead of b38.
Fixed script to only add samples to files_to_merge if QC status present.
Add printing for ids of failed samples.
Added output for projects missing QC status files.

2024-11-15 16:58 UTC, pep8speaks commented
Hello @RSWilson1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`DI-435/find_vcfs_to_merge.py`](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py):

> [Line 206:27](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L206): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 208:80](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L208): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 234:80](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L234): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 235:80](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L235): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 79 characters)
> [Line 403:80](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L403): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 414:80](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L414): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 427:80](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L427): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)

2024-11-18 10:26 UTC, rklocke requested changes
please could you do the PEP8 comments?

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-:-OByjhg57RrWHAwnn6yJ:b-3q0q6d)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @RSWilson1)

___
*[`DI-435/README.md` line 10 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-OBymRkH3O_eaAC1Tnnl:-OBymRkI7zfSOS5Zt4Kx:b8rhun1) ([raw file](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/README.md#L10)):*
> ```Markdown
> - `-a --assay`: The project prefix to look for in DNAnexus, e.g. `"*CEN38"`
> - `-o --outfile_prefix`: What to name the output TSV file which lists VCF files to merge
> - `-s --start (optional)`: A date used to find DNAnexus (GRCh37) projects created after
> ```

it would be nice to clarify here that the dates are used to find related GRCh37 projects and we are also using these to subset the b38 projects based on this
___
*[`DI-435/README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-OBylmpc4cq7Otm2AxpL:-OBylmpc4cq7Otm2AxpM:b-q4rj4p) ([raw file](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/README.md#L18)):*
> ```Markdown
> Output:
> - A TSV listing the VCF files for all non-validation samples to merge (named by `{outfile_prefix}_files_to_merge.txt`)
> - A CSV of all validation samples found (`{outfile_prefix}_validation_samples.csv`)
> ```

please could you add the missing projects file which is created here too?
___
*[`DI-435/find_vcfs_to_merge.py` line 455 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-OBykxrJANeyc4DakaZR:-OBykxrJANeyc4DakaZS:bjhb87n) ([raw file](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L455)):*
> ```Python
>     # Get list of non-failed non-validation samples to merge
>     print("Removing failed samples")
>     print(f"List of failed samples:\n{fail_sample_names}")
> ```

haven't we already printed the failed samples above where we do `print("\nFailed samples:")`?


<!-- Sent from Reviewable.io -->

2024-11-18 12:20 UTC, RSWilson1 reviewed
resolved all but one which I want to keep for clarity.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-:-OByvuZjBP9_jgxfms4l:b-n34w2m)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`DI-435/find_vcfs_to_merge.py` line 455 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-OBykxrJANeyc4DakaZR:-OBysCeOA16C4M8GXnVZ:b-ayzwz) ([raw file](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/find_vcfs_to_merge.py#L455)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

haven't we already printed the failed samples above where we do `print("\nFailed samples:")`?
</blockquote></details>

Yes that's right. I have removed it
___
*[`DI-435/README.md` line 10 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-OBymRkH3O_eaAC1Tnnl:-OByvnzj9laRgGd-_YNP:b-knzv2g) ([raw file](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/README.md#L10)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

it would be nice to clarify here that the dates are used to find related GRCh37 projects and we are also using these to subset the b38 projects based on this
</blockquote></details>

Yep I agree, added
___
*[`DI-435/README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-OBylmpc4cq7Otm2AxpL:-OByvrrq7JWcDtPdprl_:b-a52qqm) ([raw file](https://github.com/eastgenomics/RD_requests/blob/110409776f3bfd0828f0ad1012ac4c42c08176ed/DI-435/README.md#L18)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

please could you add the missing projects file which is created here too?
</blockquote></details>

yes added


<!-- Sent from Reviewable.io -->

2024-11-18 12:34 UTC, rklocke approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/14#-:-OBzF8lWCI0G0R0eNQat:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)



<!-- Sent from Reviewable.io -->

2024-11-18 12:35 UTC, merged