DI-773
eastgenomics/RD_requests pull request #3
Opened 2024-09-17 13:54 UTC by growland2

2024-09-17 13:54 UTC, pep8speaks commented
Hello @growland2! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`DI-773/qc_metrics_plotter.py`](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py):

> [Line 10:1](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 117:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 124:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L124): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 170:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L170): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 219:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L219): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 238:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L238): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (114 > 79 characters)
> [Line 245:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L245): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 251:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L251): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 261:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L261): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 266:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 311:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L311): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 326:80](https://github.com/eastgenomics/RD_requests/blob/c7c5279f1959c808457df00383c4c88ad5e40f9a/DI-773/qc_metrics_plotter.py#L326): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2024-09-18 08:59 UTC, rklocke requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/3)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @growland2)

___
*[`DI-773/qc_metrics_plotter.py` line 6 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73HScBEspYrkqzkvI1:-O73HScBEspYrkqzkvI2:b-nvl66b) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L6)):*
> ```Python
> import plotly.io as pio
> import json
> import sys
> ```

unused sys import
___
*[`DI-773/qc_metrics_plotter.py` line 45 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73GvqF2BxowIboVxWt:-O73GvqF2BxowIboVxWu:bvruid6) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L45)):*
> ```Python
> 
> def get_projects(
>     search,
> ```

could this param be renamed so it's a bit less confusing, e.g. 'search_term'?
___
*[`DI-773/qc_metrics_plotter.py` line 52 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73GlSC-cd-gUYi0CHh:-O73GlSC-cd-gUYi0CHi:b2aajuu) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L52)):*
> ```Python
> ):
>     """
>     Find projects within specified data range using specified search mode
> ```

please could you add a docstring here with parameters and returns, their types and a brief description?
___
*[`DI-773/qc_metrics_plotter.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73ILgQ4OtaIOLcCkur:-O73ILgQ4OtaIOLcCkus:b-3o6p22) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L71)):*
> ```Python
> 
> def read2df(file_id, project):
>     """Read in tsv file to df"""
> ```

docstring please
___
*[`DI-773/qc_metrics_plotter.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73I6SK16cCBD82l1OX:-O73I6SK16cCBD82l1OY:b-9ei0yw) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L105)):*
> ```Python
>     for proj in projects:
>         for key in config["file"].keys():
>             project_id = proj["id"]
> ```

`project_id = proj["id"]` should probably be moved above `for key in config["file"].keys()` so we're not initialising this for every key in the config
___
*[`DI-773/qc_metrics_plotter.py` line 116 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73Jvc8AxM9K2WjMm3w:-O73Jvc8AxM9K2WjMm3x:b-ctdnf3) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L116)):*
is the slice slightly off or am I being silly?
```
project_name = '002_240705_A01295_0391_AHFFJMDRX5_TWE'
project_name[4:-6]
>> 240705_A01295_0391_AHFFJMDR
```
___
*[`DI-773/qc_metrics_plotter.py` line 166 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73LH0a-KYsF8Pp37m1:-O73LH0a-KYsF8Pp37m2:b-pppcjz) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L166)):*
> ```Python
>                             ]
>                         )
>                     except:
> ```

might be nicer to explicitly do except on a ValueError
___
*[`DI-773/qc_metrics_plotter.py` line 342 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73Ici09lLAwRLwr9fo:-O73Ici09lLAwRLwr9fp:b-b2myut) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L342)):*
> ```Python
>             for plot_config in config["file"][key]["plots"]:
>                 make_plot(
>                         df=pd.read_csv(plot_file, sep="\t"),
> ```

this is over-indented
___
*[`DI-773/README.md` line 4 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73KkG_-E73G-f3dtCA:-O73KkG_-E73G-f3dtCB:bd6xgig) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/README.md#L4)):*
> ```Markdown
> 
> ### Original request
> Collect and plot QC metric values for each PASS/FAIL metric we use for latest 20 GRCh38 re-runs of CEN/TWE:
> ```

is this 20 or 10? it says 10 in each config
___
*[`DI-773/README.md` line 27 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73Kpo84CSjdLwKcv6w:-O73Kpo9AtoZpNTavJO_:b-ymn4xv) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/README.md#L27)):*
> ```Markdown
> ### Running
> Example command:
> `python3 'qc_metrics_plotter.py' -c 'qc_threshold_config_cen.json' -r 'gather_and_plot'`
> ```

no need for quotes around each bit:
`python3 qc_metrics_plotter.py -c qc_metrics_plotter_config_CEN.json -r gather_and_plot`
___
*[`DI-773/README.md` line 32 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73L5nZ5sUn7MqjTtUM:-O73L5nZ5sUn7MqjTtUN:b55j32n) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/README.md#L32)):*
> ```Markdown
> The script:
> 1. Searches for desired projects according to search parameters defined in the "project_search" section of the config
> 2. Within the projects found above, finds all desired QC files as specified in the "file" section of the config and reads the files in as panda dataframes. *Note: every file except QC Status.xlsx's can be accessed via dxpy. Due to an encoding problem / unreadable byte, the QC status .xlsx's are downloaded locally first, then read in*
> ```

this bit about QC status xlsx files being downloaded can be removed now right?


<!-- Sent from Reviewable.io -->

2024-09-18 09:27 UTC, growland2 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/3)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @rklocke)

___
*[`DI-773/qc_metrics_plotter.py` line 6 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73HScBEspYrkqzkvI1:-O73MoQCCHncL5SIVJOy:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L6)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

unused sys import
</blockquote></details>

Done.
___
*[`DI-773/qc_metrics_plotter.py` line 45 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73GvqF2BxowIboVxWt:-O73NM0e1CNbwe0TEFeu:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L45)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

could this param be renamed so it's a bit less confusing, e.g. 'search_term'?
</blockquote></details>

Done.
___
*[`DI-773/qc_metrics_plotter.py` line 52 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73GlSC-cd-gUYi0CHh:-O73P4TB0CfZQbbc6Ju3:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L52)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

please could you add a docstring here with parameters and returns, their types and a brief description?
</blockquote></details>

Done.
___
*[`DI-773/qc_metrics_plotter.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73ILgQ4OtaIOLcCkur:-O73PpDb8fhm_wVkXoMJ:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L71)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

docstring please
</blockquote></details>

Done.
___
*[`DI-773/qc_metrics_plotter.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73I6SK16cCBD82l1OX:-O73Q9g35WFvYz-d1YB7:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L105)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

`project_id = proj["id"]` should probably be moved above `for key in config["file"].keys()` so we're not initialising this for every key in the config
</blockquote></details>

Done.
___
*[`DI-773/qc_metrics_plotter.py` line 116 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73Jvc8AxM9K2WjMm3w:-O73Qh4V-QOn3LjGfNy1:bndq3k1) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L116)):*
we are using 38 project names:

```
 project_name = "038_240619_A01295_0384_AHCJ2FDRX5_CEN38"
>>> project_name[4:-6]
'240619_A01295_0384_AHCJ2FDRX5'
```
___
*[`DI-773/qc_metrics_plotter.py` line 166 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73LH0a-KYsF8Pp37m1:-O73RAAX314_kIzFT1vf:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L166)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

might be nicer to explicitly do except on a ValueError
</blockquote></details>

Done.
___
*[`DI-773/qc_metrics_plotter.py` line 342 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73Ici09lLAwRLwr9fo:-O73RMnnBgyWjLA7qNuE:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/qc_metrics_plotter.py#L342)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

this is over-indented
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 09:30 UTC, growland2 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/3)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @rklocke)

___
*[`DI-773/README.md` line 4 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73KkG_-E73G-f3dtCA:-O73Su_m1tODOAFwMGLL:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/README.md#L4)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

is this 20 or 10? it says 10 in each config
</blockquote></details>

Done.
___
*[`DI-773/README.md` line 27 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73Kpo84CSjdLwKcv6w:-O73SyJd1IKVwGF4jvWy:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/README.md#L27)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

no need for quotes around each bit:
`python3 qc_metrics_plotter.py -c qc_metrics_plotter_config_CEN.json -r gather_and_plot`
</blockquote></details>

Done.
___
*[`DI-773/README.md` line 32 at r2](https://reviewable.io/reviews/eastgenomics/RD_requests/3#-O73L5nZ5sUn7MqjTtUM:-O73T0ilB24vvVM5NjSx:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b2ce440558eb38f67c3c22878b4998f425d9ccfb/DI-773/README.md#L32)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

this bit about QC status xlsx files being downloaded can be removed now right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-18 11:07 UTC, merged