B38 sex check
eastgenomics/RD_requests pull request #8
Opened 2024-10-02 08:49 UTC by pofuoku

Add a folder for b38 sex check thresholds request
@rklocke

2024-10-02 08:50 UTC, pep8speaks commented
Hello @pofuoku! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`DI-1094/get_somalier_pred.py`](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py):

> [Line 23:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L23): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`DI-1094/plot_sex_check_thresholds.py`](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py):

> [Line 4:74](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L4): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 22:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 25:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L25): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 48:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L48): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 53:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L53): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 106:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 108:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L108): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 118:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 124:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L124): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 153:38](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L153): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 162:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L162): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 207:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L207): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 214:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L214): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 225:41](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L225): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 255:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L255): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 262:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L262): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 275:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L275): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 284:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L284): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)

* In the file [`DI-1094/run_sex_check.py`](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py):

> [Line 16:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 50:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L50): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 102:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 112:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L112): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 120:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L120): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 129:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L129): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 145:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L145): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 146:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L146): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 148:80](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L148): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)

2024-10-02 11:11 UTC, rklocke requested changes
please could you address (at least some) of the PEP8 issues?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-:-O8BkULW0iLY98uXmcnx:b-dcrgoa)* status: all files reviewed, 7 unresolved discussions (waiting on @pofuoku)

___
*[`DI-1094/get_somalier_pred.py` line 10 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BhU_NAqMhGfe-PaBw:-O8BhU_NAqMhGfe-PaBx:brdo9bo) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L10)):*
> ```Python
> 
> def find_somalier_report(project_id: str) -> pd.DataFrame:
>     """
> ```

please could you add a docstring with Args and Returns?
___
*[`DI-1094/get_somalier_pred.py` line 47 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BhZJf26joeVj3A139:-O8BhZJf26joeVj3A13A:brdo9bo) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L47)):*
> ```Python
> 
> 
> def read_somalier_report(file_id: str, project_id: str) -> pd.DataFrame:
> ```

please could you add a docstring with Args and Returns?
___
*[`DI-1094/get_somalier_pred.py` line 59 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8Bhchu-huzA2eBeKKR:-O8Bhchv-BZzTP3Kn9a0:bukww7w) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L59)):*
> ```Python
>     df = pd.read_csv("dias_b38_samples.csv")
> 
>     df = pd.concat(
> ```

it is slightly confusing having the `df` variable keep being reassigned, please could you name the dataframes differently?
e.g.
```
dias_samples = pd.read_csv('dias_b38_samples.csv')
merged_somalier_reports = pd.concat(
    [find_somalier_report(proj) for proj in dias_samples.project_id.unique()],
    ignore_index=True
)
```
___
*[`DI-1094/plot_sex_check_thresholds.py` line 90 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BuKXj9Eq1V-FGIE8k:-O8BuKXj9Eq1V-FGIE8l:b6wt1fz) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L90)):*
> ```Python
>         Tuple[Dict[str, str], Dict[str, str]]: Mappings for run and date.
>     """
>     samples_to_run = {row["samples"]: row["run"] for _, row in df.iterrows()}
> ```

is making the sample mappings here and in function below easier than just merging multiple dataframes by sample_id later? (if so, not saying you have to do this since this is a one-off thing, but something to consider in future)
___
*[`DI-1094/run_sex_check.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BmND23MDH_MSQFFG2:-O8BmND23MDH_MSQFFG3:bw1pq6v) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L12)):*
> ```Python
> 
> def get_project_ids(pattern: str) -> list:
>     """
> ```

please add Args and Returns in the docstrings in this script
___
*[`DI-1094/run_sex_check.py` line 194 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BuoRV0kNqoO72L8uh:-O8BuoRV0kNqoO72L8ui:b-icgzyt) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L194)):*
> ```Python
> 
>         # Set thresholds based on assay type
>         male_threshold = 4.40 if assay == "CEN38" else 4.05
> ```

are these ok to be harcoded? (genuinely asking as I don't know if these are always the same)
___
*[`DI-1094/run_sex_check.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BqQvJ1OFI7LnVLFIb:-O8BqQvJ1OFI7LnVLFIc:b-9s49md) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L198)):*
> ```Python
> 
>         # Construct dx run command
>         dx_command = [
> ```

is there a reason you're running this with subprocess and not just setting off the job using dxpy, e.g.:
```
dxpy.DXApp(name='eggd_sex_check').run(
    app_input={
        "input_bam": ...,
        "index_file": ....,
        "male_threshold": .....,
        "female_threshold" :.....
    },
    project=project,
    folder=f"/output/{assay}/{row["project_name"]",
    name=f"{assay}_threshold"
)
```
Docs: http://autodoc.dnanexus.com/bindings/python/current/dxpy_apps.html#dxpy.bindings.dxapplet.DXExecutable.run


<!-- Sent from Reviewable.io -->

2024-10-03 11:06 UTC, pofuoku reviewed
I've fixed most of them. Majority of them are so trivial eg one or two xters being too long.
In addition, I formatted the code with Black but it seems PEP8 has its own opinions.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-:-O8H0pHM3bfNcbvSF9rG:bv6ksfn)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @rklocke)

___
*[`DI-1094/get_somalier_pred.py` line 10 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BhU_NAqMhGfe-PaBw:-O8H1HKM63WYQNcuGqWl:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L10)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

please could you add a docstring with Args and Returns?
</blockquote></details>

Done.
___
*[`DI-1094/get_somalier_pred.py` line 47 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BhZJf26joeVj3A139:-O8H1IWb3W_Y33NJeF-i:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L47)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

please could you add a docstring with Args and Returns?
</blockquote></details>

Done.
___
*[`DI-1094/get_somalier_pred.py` line 59 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8Bhchu-huzA2eBeKKR:-O8H1Jct0GzyF8VHQexK:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/get_somalier_pred.py#L59)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

it is slightly confusing having the `df` variable keep being reassigned, please could you name the dataframes differently?
e.g.
```
dias_samples = pd.read_csv('dias_b38_samples.csv')
merged_somalier_reports = pd.concat(
    [find_somalier_report(proj) for proj in dias_samples.project_id.unique()],
    ignore_index=True
)
```
</blockquote></details>

Done.
___
*[`DI-1094/plot_sex_check_thresholds.py` line 90 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BuKXj9Eq1V-FGIE8k:-O8GZOXV-dzT86aL0I6o:b-ahlnyl) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/plot_sex_check_thresholds.py#L90)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

is making the sample mappings here and in function below easier than just merging multiple dataframes by sample_id later? (if so, not saying you have to do this since this is a one-off thing, but something to consider in future)
</blockquote></details>

Either method work but I find it easier using a mapping. The Map contains all DIAS samples and have cols ,which I do not need, while the df I'm applying them is for a particular assay, I can subset the df before merging like you suggested but it's a bit more work in my opinion because I have to still select the cols and rows I need and consider the assay. The mappings, on the other hand, works out of the box. 
___
*[`DI-1094/run_sex_check.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BmND23MDH_MSQFFG2:-O8H1N7Y2wBqBr4YfPnP:b-aoj698) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L12)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

please add Args and Returns in the docstrings in this script
</blockquote></details>

I have added Args and Returns to the docstring. The reason, I omitted them initially was because, it added some unnecessary verbosity. Taking a leaf from our last Python training -- I had reasoned most of the Args are self defined and are being repeated too many times throughout the script. But I've now had a rethink and updated the docstring for style consistency.
___
*[`DI-1094/run_sex_check.py` line 194 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BuoRV0kNqoO72L8uh:-O8GqeJ1CF9MGGQkUOTQ:b-3oswdq) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L194)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

are these ok to be harcoded? (genuinely asking as I don't know if these are always the same)
</blockquote></details>

I think it's okay for them to be hardcoded in this context. The thresholds are just for the app to run and produce a score for each sample. The main aim of this task is to find a threshold to use in prod (using the output scores from the app). So at this stage the thresholds that set off the jobs are not important.

I've added a comment to clarify that the thresholds were chosen arbitrary.
___
*[`DI-1094/run_sex_check.py` line 198 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/8#-O8BqQvJ1OFI7LnVLFIb:-O8GswKu93OoNggrxSQr:bwxrn5h) ([raw file](https://github.com/eastgenomics/RD_requests/blob/14abb85fd5f543631e51fb9dab4004f7888a18f4/DI-1094/run_sex_check.py#L198)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

is there a reason you're running this with subprocess and not just setting off the job using dxpy, e.g.:
```
dxpy.DXApp(name='eggd_sex_check').run(
    app_input={
        "input_bam": ...,
        "index_file": ....,
        "male_threshold": .....,
        "female_threshold" :.....
    },
    project=project,
    folder=f"/output/{assay}/{row["project_name"]",
    name=f"{assay}_threshold"
)
```
Docs: http://autodoc.dnanexus.com/bindings/python/current/dxpy_apps.html#dxpy.bindings.dxapplet.DXExecutable.run
</blockquote></details>

No concrete reason, it was more of a preference at the time, I first worked on this project. It seemed more intuitive to copy and paste the dx command I first used and wasn't used to dxpy then. I also had a tiny concern running an older version of the app then and appending the version on the dx command solved it. Now I'm more familiar with dxpy but still did n't see the need to change it. But styles work but the dx command is just a bit more concise and cleaner, IMO.

Do you have any particular reason against this pattern ?


<!-- Sent from Reviewable.io -->

2024-10-03 11:31 UTC, rklocke approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pofuoku)



<!-- Sent from Reviewable.io -->

2024-10-03 11:31 UTC, merged